parameters:
#    cupon_backend.example.class: Cupon\BackendBundle\Example

services:
#    cupon_backend.example:
#        class: %cupon_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
